name: ioe
channels:
  - conda-forge
dependencies:
  - pip=21.1.3
  - redis-py=3.5.3
  - redisgraph-py=2.4.0
  - pandapower=2.6.0
  - pip:
    - ruamel.yaml==0.17.10
    - ruamel.yaml.clib==0.2.6
    - pyyaml==5.4.1
    - rejson==0.5.4
    - tornado==6.1
    - pybase64==1.1.4
    - pycryptodome==3.10.1
